import * as React from 'react';

export default function SurfSpotSection({ annotationPrefix, body }) {
    return (
        <div data-sb-field-path={annotationPrefix}>
            <p data-sb-field-path=".body">{body}</p>
        <p class=\"mb-2\">Airport Rights' surf is an intermediate right reef break.</p>\n    \n    <p class=\"mb-2\">The waves at Airport Rights are at their best with a 13 to 16 second Southwest swell at around 3 to 5 feet. If you get it with a light East wind at low tide, it’ll be close to as good as it gets — it’s a 4 star surf spot, so that means the surf would be insanely fun for intermediate surfers.</p>\n    \n    <p class=\"mb-2\">The best time to surf Airport Rights is in May, June, July or August.</p>\n\n    <p class=\"mb-2\">\n      <p class=\"mb-2\">Watch this video of Airport Rights' surf to get a better feel for what the waves are like.</p>\n      <iframe class=\"mb-2\" width=\"560\" height=\"315\" src=\"https://www.youtube-nocookie.com/embed/ccs-8o-T1CE\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n      <p class=\"mb-2\"> Remember, this is just one day. Always check the surf report before going. You can <a href=\"https://www.google.com/search?q=Airport Rights%20surf&tbm=vid\" target=\"_blank\">watch other videos of Airport Rights' surf here</a>.</p>\n    </p>\n\n    <p class=\"mb-2\">You can <a href=\"https://magicseaweed.com/Airport-Reef-Surf-Report/2309/\" target=\"_blank\">find Airport Rights' surf report and surf forecast here.</a></p>\n\n    <p class=\"mb-2\">To learn where to surf in Airport Rights' line up, check out our surf map below which shows all of Airport Rights' surf spots or breaks.</p>\n\n    <p class=\"mb-2\">Get Google Maps directions right to Airport Rights' parking lot by clicking the “Get Directions” button.\n    </p>\n\n    <p class=\"mb-2\">Get information about the surf spots nearby Airport Rights in the sidebar (below on mobile) or on our surf map page.</p>\n\n    <p class=\"mb-2\">Feel free to email us at surftriplist @ gmail to help improve this information.</p>
        </div>
    )
}